apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajob-fe
  labels:
    app: microservices
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: microservices
        tier: frontend
    spec:
      containers:
        - name: view
          image: ghcr.io/haikaljavierrachman/karsajobs-ui:latest
          env:
            - name: VUE_APP_BACKEND
              value: http://karsajob-be.default:8080
