name: karsajobs-ui-ci
  
on: 
  push:
    branches: 
      - karsajobs-ui
  pull_request:
    branches: 
      - karsajobs-ui

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4

      - name: lint dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
        
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}

      -
        name: Build and Push
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/haikaljavierrachman/karsajobs-ui:latest
